### PR TITLE
unify app structure

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by paveljanda** [comment]
Why did this happen?

https://github.com/nette/web-project

Why are we using `var`? That is not a developer neither nette standard.

**Comment by petrparolek** [comment]
@f3l1x  I agree with @paveljanda . Why do you use new app structure?

**Comment by paveljanda** [comment]
Referring to another comment of mine, I wrote there a bit longer explanation: https://github.com/contributte/datagrid-skeleton/pull/13#issuecomment-998832240

**Comment by paveljanda** [comment]
ping @f3l1x

**Pull request merged**
